---
- name: Security Rule Facts
  hosts: check_point
  connection: httpapi
  gather_facts: false

  tasks:
    - name: verify-policy
      cp_mgmt_verify_policy:
        policy_package: Remote_Policy
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "result.verify-policy"
